/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfas_alumno;

/**
 *
 * @author liooficial
 */
public class Notificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Notificaciones() {
        initComponents();
         this.setLocationRelativeTo(null);
         rsscalelabel.RSScaleLabel.setScaleLabel(lb_logoImg,"src/img/isc.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(lb_administrarImg,"src/img/calendario.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(lb_administrarUsuarioImg,"src/img/grupo-de-usuarios.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(lb_reportesimg,"src/img/reporte2.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(lb_rondinesimg,"src/img/ronda.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(lb_notificacionesimg,"src/img/correo.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(lb_invetaimg,"src/img/inventario.png");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_principal = new javax.swing.JPanel();
        pn_menuLateral = new javax.swing.JPanel();
        lb_administrarImg = new javax.swing.JLabel();
        lb_logoImg = new javax.swing.JLabel();
        lb_administrarUsuarioImg = new javax.swing.JLabel();
        lb_reportesimg = new javax.swing.JLabel();
        lb_rondinesimg = new javax.swing.JLabel();
        lb_notificacionesimg = new javax.swing.JLabel();
        lb_invetaimg = new javax.swing.JLabel();
        bt_administrar_Horarios = new javax.swing.JToggleButton();
        bt_administrar_Usuarios = new javax.swing.JToggleButton();
        bt_reportes = new javax.swing.JToggleButton();
        bt_rondines = new javax.swing.JToggleButton();
        bt_notificaciones = new javax.swing.JToggleButton();
        lb_inventario = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_principal.setBackground(new java.awt.Color(255, 255, 255));

        pn_menuLateral.setBackground(new java.awt.Color(255, 255, 255));
        pn_menuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_administrarImg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_administrarImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pn_menuLateral.add(lb_administrarImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 40));
        pn_menuLateral.add(lb_logoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 140));

        lb_administrarUsuarioImg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_administrarUsuarioImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_administrarUsuarioImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, 40));

        lb_reportesimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_reportesimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_reportesimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 70, 40));

        lb_rondinesimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_rondinesimg.setText(" ");
        lb_rondinesimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_rondinesimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 70, 40));

        lb_notificacionesimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_notificacionesimg.setText(" ");
        lb_notificacionesimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_notificacionesimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 70, 40));

        lb_invetaimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_invetaimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_invetaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 70, 40));

        bt_administrar_Horarios.setBackground(new java.awt.Color(255, 255, 255));
        bt_administrar_Horarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_administrar_Horarios.setText("Tipo de notificacion ");
        bt_administrar_Horarios.setBorder(null);
        bt_administrar_Horarios.setContentAreaFilled(false);
        bt_administrar_Horarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_administrar_Horarios.setFocusPainted(false);
        bt_administrar_Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrar_HorariosActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_administrar_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 330, 60));

        bt_administrar_Usuarios.setBackground(new java.awt.Color(255, 255, 255));
        bt_administrar_Usuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_administrar_Usuarios.setText("Redactar notificacion ");
        bt_administrar_Usuarios.setContentAreaFilled(false);
        bt_administrar_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_administrar_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrar_UsuariosActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_administrar_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 350, 60));

        bt_reportes.setBackground(new java.awt.Color(255, 255, 255));
        bt_reportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_reportes.setText("Eliminar Notificacion ");
        bt_reportes.setContentAreaFilled(false);
        bt_reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reportesActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 350, 60));

        bt_rondines.setBackground(new java.awt.Color(255, 255, 255));
        bt_rondines.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_rondines.setText("Mostrar Notificacion  ");
        bt_rondines.setContentAreaFilled(false);
        bt_rondines.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(bt_rondines, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 350, 60));

        bt_notificaciones.setBackground(new java.awt.Color(255, 255, 255));
        bt_notificaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_notificaciones.setText("    Salir ");
        bt_notificaciones.setContentAreaFilled(false);
        bt_notificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(bt_notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 350, 60));

        lb_inventario.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lb_inventario.setText("Notificaciones");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_principalLayout = new javax.swing.GroupLayout(pn_principal);
        pn_principal.setLayout(pn_principalLayout);
        pn_principalLayout.setHorizontalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addComponent(pn_menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_principalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_inventario))
                    .addGroup(pn_principalLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(749, Short.MAX_VALUE))
        );
        pn_principalLayout.setVerticalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addComponent(pn_menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_inventario)
                .addGap(123, 123, 123)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_administrar_HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrar_HorariosActionPerformed
        
    }//GEN-LAST:event_bt_administrar_HorariosActionPerformed

    private void bt_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_reportesActionPerformed

    private void bt_administrar_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrar_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_administrar_UsuariosActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_administrar_Horarios;
    private javax.swing.JToggleButton bt_administrar_Usuarios;
    private javax.swing.JToggleButton bt_notificaciones;
    private javax.swing.JToggleButton bt_reportes;
    private javax.swing.JToggleButton bt_rondines;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lb_administrarImg;
    private javax.swing.JLabel lb_administrarUsuarioImg;
    private javax.swing.JLabel lb_inventario;
    private javax.swing.JLabel lb_invetaimg;
    private javax.swing.JLabel lb_logoImg;
    private javax.swing.JLabel lb_notificacionesimg;
    private javax.swing.JLabel lb_reportesimg;
    private javax.swing.JLabel lb_rondinesimg;
    private javax.swing.JPanel pn_menuLateral;
    private javax.swing.JPanel pn_principal;
    // End of variables declaration//GEN-END:variables
}
